/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AuthenticatedUsageRouteImport } from './routes/_authenticated/usage'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedTradesIndexRouteImport } from './routes/_authenticated/trades/index'
import { Route as AuthenticatedPositionsIndexRouteImport } from './routes/_authenticated/positions/index'
import { Route as AuthenticatedTradesNewRouteImport } from './routes/_authenticated/trades/new'
import { Route as AuthenticatedTradesFromSlipRouteImport } from './routes/_authenticated/trades/from-slip'
import { Route as AuthenticatedPositionsTickerRouteImport } from './routes/_authenticated/positions/$ticker'
import { Route as AuthenticatedDevArtifactsRouteImport } from './routes/_authenticated/dev/artifacts'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignUpRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignInRoute,
} as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTradesIndexRoute =
  AuthenticatedTradesIndexRouteImport.update({
    id: '/trades/',
    path: '/trades/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPositionsIndexRoute =
  AuthenticatedPositionsIndexRouteImport.update({
    id: '/positions/',
    path: '/positions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTradesNewRoute = AuthenticatedTradesNewRouteImport.update({
  id: '/trades/new',
  path: '/trades/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTradesFromSlipRoute =
  AuthenticatedTradesFromSlipRouteImport.update({
    id: '/trades/from-slip',
    path: '/trades/from-slip',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPositionsTickerRoute =
  AuthenticatedPositionsTickerRouteImport.update({
    id: '/positions/$ticker',
    path: '/positions/$ticker',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDevArtifactsRoute =
  AuthenticatedDevArtifactsRouteImport.update({
    id: '/dev/artifacts',
    path: '/dev/artifacts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/chat': typeof AuthenticatedChatRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dev/artifacts': typeof AuthenticatedDevArtifactsRoute
  '/positions/$ticker': typeof AuthenticatedPositionsTickerRoute
  '/trades/from-slip': typeof AuthenticatedTradesFromSlipRoute
  '/trades/new': typeof AuthenticatedTradesNewRoute
  '/positions/': typeof AuthenticatedPositionsIndexRoute
  '/trades/': typeof AuthenticatedTradesIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/chat': typeof AuthenticatedChatRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/': typeof AuthenticatedIndexRoute
  '/dev/artifacts': typeof AuthenticatedDevArtifactsRoute
  '/positions/$ticker': typeof AuthenticatedPositionsTickerRoute
  '/trades/from-slip': typeof AuthenticatedTradesFromSlipRoute
  '/trades/new': typeof AuthenticatedTradesNewRoute
  '/positions': typeof AuthenticatedPositionsIndexRoute
  '/trades': typeof AuthenticatedTradesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/usage': typeof AuthenticatedUsageRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/dev/artifacts': typeof AuthenticatedDevArtifactsRoute
  '/_authenticated/positions/$ticker': typeof AuthenticatedPositionsTickerRoute
  '/_authenticated/trades/from-slip': typeof AuthenticatedTradesFromSlipRoute
  '/_authenticated/trades/new': typeof AuthenticatedTradesNewRoute
  '/_authenticated/positions/': typeof AuthenticatedPositionsIndexRoute
  '/_authenticated/trades/': typeof AuthenticatedTradesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/welcome'
    | '/chat'
    | '/usage'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dev/artifacts'
    | '/positions/$ticker'
    | '/trades/from-slip'
    | '/trades/new'
    | '/positions/'
    | '/trades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/welcome'
    | '/chat'
    | '/usage'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/'
    | '/dev/artifacts'
    | '/positions/$ticker'
    | '/trades/from-slip'
    | '/trades/new'
    | '/positions'
    | '/trades'
  id:
    | '__root__'
    | '/_authenticated'
    | '/sign-in'
    | '/sign-up'
    | '/welcome'
    | '/_authenticated/chat'
    | '/_authenticated/usage'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_authenticated/'
    | '/_authenticated/dev/artifacts'
    | '/_authenticated/positions/$ticker'
    | '/_authenticated/trades/from-slip'
    | '/_authenticated/trades/new'
    | '/_authenticated/positions/'
    | '/_authenticated/trades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof SignInRoute
    }
    '/_authenticated/usage': {
      id: '/_authenticated/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trades/': {
      id: '/_authenticated/trades/'
      path: '/trades'
      fullPath: '/trades/'
      preLoaderRoute: typeof AuthenticatedTradesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/positions/': {
      id: '/_authenticated/positions/'
      path: '/positions'
      fullPath: '/positions/'
      preLoaderRoute: typeof AuthenticatedPositionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trades/new': {
      id: '/_authenticated/trades/new'
      path: '/trades/new'
      fullPath: '/trades/new'
      preLoaderRoute: typeof AuthenticatedTradesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trades/from-slip': {
      id: '/_authenticated/trades/from-slip'
      path: '/trades/from-slip'
      fullPath: '/trades/from-slip'
      preLoaderRoute: typeof AuthenticatedTradesFromSlipRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/positions/$ticker': {
      id: '/_authenticated/positions/$ticker'
      path: '/positions/$ticker'
      fullPath: '/positions/$ticker'
      preLoaderRoute: typeof AuthenticatedPositionsTickerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dev/artifacts': {
      id: '/_authenticated/dev/artifacts'
      path: '/dev/artifacts'
      fullPath: '/dev/artifacts'
      preLoaderRoute: typeof AuthenticatedDevArtifactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDevArtifactsRoute: typeof AuthenticatedDevArtifactsRoute
  AuthenticatedPositionsTickerRoute: typeof AuthenticatedPositionsTickerRoute
  AuthenticatedTradesFromSlipRoute: typeof AuthenticatedTradesFromSlipRoute
  AuthenticatedTradesNewRoute: typeof AuthenticatedTradesNewRoute
  AuthenticatedPositionsIndexRoute: typeof AuthenticatedPositionsIndexRoute
  AuthenticatedTradesIndexRoute: typeof AuthenticatedTradesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDevArtifactsRoute: AuthenticatedDevArtifactsRoute,
  AuthenticatedPositionsTickerRoute: AuthenticatedPositionsTickerRoute,
  AuthenticatedTradesFromSlipRoute: AuthenticatedTradesFromSlipRoute,
  AuthenticatedTradesNewRoute: AuthenticatedTradesNewRoute,
  AuthenticatedPositionsIndexRoute: AuthenticatedPositionsIndexRoute,
  AuthenticatedTradesIndexRoute: AuthenticatedTradesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SignInRouteChildren {
  SignInSplatRoute: typeof SignInSplatRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSplatRoute: SignInSplatRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface SignUpRouteChildren {
  SignUpSplatRoute: typeof SignUpSplatRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpSplatRoute: SignUpSplatRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
