/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradesIndexRouteImport } from './routes/trades/index'
import { Route as PositionsIndexRouteImport } from './routes/positions/index'
import { Route as TradesNewRouteImport } from './routes/trades/new'
import { Route as PositionsTickerRouteImport } from './routes/positions/$ticker'

const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesIndexRoute = TradesIndexRouteImport.update({
  id: '/trades/',
  path: '/trades/',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsIndexRoute = PositionsIndexRouteImport.update({
  id: '/positions/',
  path: '/positions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesNewRoute = TradesNewRouteImport.update({
  id: '/trades/new',
  path: '/trades/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsTickerRoute = PositionsTickerRouteImport.update({
  id: '/positions/$ticker',
  path: '/positions/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/positions/$ticker': typeof PositionsTickerRoute
  '/trades/new': typeof TradesNewRoute
  '/positions/': typeof PositionsIndexRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/positions/$ticker': typeof PositionsTickerRoute
  '/trades/new': typeof TradesNewRoute
  '/positions': typeof PositionsIndexRoute
  '/trades': typeof TradesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/positions/$ticker': typeof PositionsTickerRoute
  '/trades/new': typeof TradesNewRoute
  '/positions/': typeof PositionsIndexRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/positions/$ticker'
    | '/trades/new'
    | '/positions/'
    | '/trades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/positions/$ticker'
    | '/trades/new'
    | '/positions'
    | '/trades'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/positions/$ticker'
    | '/trades/new'
    | '/positions/'
    | '/trades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  PositionsTickerRoute: typeof PositionsTickerRoute
  TradesNewRoute: typeof TradesNewRoute
  PositionsIndexRoute: typeof PositionsIndexRoute
  TradesIndexRoute: typeof TradesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/': {
      id: '/trades/'
      path: '/trades'
      fullPath: '/trades/'
      preLoaderRoute: typeof TradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions/': {
      id: '/positions/'
      path: '/positions'
      fullPath: '/positions/'
      preLoaderRoute: typeof PositionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/new': {
      id: '/trades/new'
      path: '/trades/new'
      fullPath: '/trades/new'
      preLoaderRoute: typeof TradesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions/$ticker': {
      id: '/positions/$ticker'
      path: '/positions/$ticker'
      fullPath: '/positions/$ticker'
      preLoaderRoute: typeof PositionsTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  PositionsTickerRoute: PositionsTickerRoute,
  TradesNewRoute: TradesNewRoute,
  PositionsIndexRoute: PositionsIndexRoute,
  TradesIndexRoute: TradesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
